/**
 * 넥슨 이벤트 보상 시스템 표준 에러 코드
 * 
 * 각 마이크로서비스에서 사용할 표준화된 에러 코드를 정의합니다.
 * 코드 형식: [서비스명]_[카테고리]_[세부코드]
 */

// 공통 시스템 에러
export enum SystemErrorCodes {
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  INVALID_REQUEST = 'INVALID_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}

// 인증 관련 에러
export enum AuthErrorCodes {
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
}

// 이벤트 관련 에러
export enum EventErrorCodes {
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  EVENT_ALREADY_EXISTS = 'EVENT_ALREADY_EXISTS',
  EVENT_INACTIVE = 'EVENT_INACTIVE',
  EVENT_EXPIRED = 'EVENT_EXPIRED',
  EVENT_CONDITION_INVALID = 'EVENT_CONDITION_INVALID',
  EVENT_DATE_INVALID = 'EVENT_DATE_INVALID',
}

// 보상 관련 에러
export enum RewardErrorCodes {
  REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
  REWARD_ALREADY_EXISTS = 'REWARD_ALREADY_EXISTS',
  REWARD_INVALID_TYPE = 'REWARD_INVALID_TYPE',
  REWARD_INSUFFICIENT_AMOUNT = 'REWARD_INSUFFICIENT_AMOUNT',
}

// 청구 관련 에러
export enum ClaimErrorCodes {
  CLAIM_NOT_FOUND = 'CLAIM_NOT_FOUND',
  CLAIM_ALREADY_EXISTS = 'CLAIM_ALREADY_EXISTS',
  CLAIM_ALREADY_PROCESSED = 'CLAIM_ALREADY_PROCESSED',
  CLAIM_CONDITION_NOT_MET = 'CLAIM_CONDITION_NOT_MET',
  CLAIM_INVALID_USER = 'CLAIM_INVALID_USER',
  CLAIM_EXPIRED = 'CLAIM_EXPIRED',
  CLAIM_PENDING_APPROVAL = 'CLAIM_PENDING_APPROVAL',
}

// 게이트웨이 관련 에러
export enum GatewayErrorCodes {
  GATEWAY_SERVICE_UNAVAILABLE = 'GATEWAY_SERVICE_UNAVAILABLE',
  GATEWAY_INVALID_RESPONSE = 'GATEWAY_INVALID_RESPONSE',
  GATEWAY_REQUEST_TIMEOUT = 'GATEWAY_REQUEST_TIMEOUT',
}

// 모든 에러 코드 타입 통합
export type ErrorCode =
  | SystemErrorCodes
  | AuthErrorCodes
  | EventErrorCodes
  | RewardErrorCodes
  | ClaimErrorCodes
  | GatewayErrorCodes
  | string; // 기타 에러 코드를 위한 확장성 제공 